import { test, expect } from '@playwright/test';
test('full journey: records, history, schedules, filters and deletion', async ({ page }, testInfo) => {
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  const company = `旅程科技-${testInfo.project.name}`;
  await page.goto('/');
  await expect(page).toHaveURL('http://127.0.0.1:3101/');
  await expect(page.locator('input[type=password]')).toHaveCount(0);
  await expect(page.getByRole('heading', { name: '每一步，都有迹可循。' })).toBeVisible();
  await page.getByRole('button', { name: '新增投递', exact: true }).click();
  const editor = page.locator('#editor-dialog');
  await editor.getByLabel('公司名称').fill(company);
  await editor.getByLabel('岗位名称').fill('前端开发工程师');
  await editor.getByLabel('当前进度').selectOption('已投递');
  await editor.getByLabel('投递时间（北京时间）', { exact: true }).fill('2026-09-01T10:30');
  await editor.getByLabel('岗位链接').fill('https://example.com/jobs/123');
  await editor.getByLabel('备注', { exact: true }).fill('<script>alert(1)</script>准备项目介绍');
  await editor.getByRole('button', { name: '保存', exact: true }).click();
  await expect(editor).not.toBeVisible();
  await page.getByRole('button', { name: company, exact: true }).click();
  const detail = page.locator('#detail-dialog');
  await expect(detail.getByRole('heading', { name: company, exact: true })).toBeVisible();
  await expect(detail.getByText('<script>alert(1)</script>准备项目介绍')).toBeVisible();
  await detail.getByRole('button', { name: '编辑投递 / 更新进度' }).click();
  await editor.getByLabel('当前进度').selectOption('一面');
  await editor.getByRole('button', { name: '保存', exact: true }).click();
  await expect(editor).not.toBeVisible();
  await expect(detail.locator('.timeline li')).toHaveCount(2);
  await detail.locator('.timeline li').first().getByRole('button', { name: '纠正' }).click();
  await editor.getByLabel('进度', { exact: true }).selectOption('二面');
  await editor.getByLabel('流程备注').fill('修正进度');
  await editor.getByRole('button', { name: '保存', exact: true }).click();
  await expect(editor).not.toBeVisible();
  await expect(detail.locator('.detail-info')).toContainText('二面');
  await detail.getByRole('button', { name: '添加日程' }).click();
  await editor.getByLabel('日程名称').fill('技术二面');
  const tomorrow = new Date(Date.now() + 86400000 + 8 * 3600000).toISOString().slice(0, 16);
  await editor.getByLabel('安排时间 / 截止时间（北京时间）').fill(tomorrow);
  await editor.getByRole('button', { name: '保存', exact: true }).click();
  await expect(editor).not.toBeVisible();
  await expect(detail.getByRole('heading', { name: '技术二面', exact: true })).toBeVisible();
  await detail.getByRole('button', { name: '关闭详情' }).click();
  await expect(page.locator('#reminders')).toContainText(company);
  await page.locator('.sidebar').getByRole('button', { name: '日程安排' }).click();
  const row = page.locator('.event-row').filter({ hasText: company });
  await row.getByRole('button', { name: '完成', exact: true }).click();
  await expect(row).toHaveCount(0);
  await page.getByLabel('查看范围').selectOption('completed');
  await expect(page.locator('#schedule-list')).toContainText('技术二面');
  await page.locator('.sidebar').getByRole('button', { name: '投递总览' }).click();
  await page.getByLabel('搜索公司或岗位').fill(company);
  await expect(page.locator('.application-table tbody tr')).toHaveCount(1);
  await page.getByRole('button', { name: '看板', exact: true }).click();
  await expect(page.locator('.board-card')).toHaveCount(1);
  await expect(page.locator('.board-column').filter({ hasText: '二面' }).locator('.board-card')).toHaveCount(1);
  await page.getByRole('button', { name: '列表', exact: true }).click();
  await page.getByLabel('投递起始日期').fill('2026-09-02');
  await expect(page.getByText('没有找到匹配的投递')).toBeVisible();
  await page.getByRole('button', { name: '重置', exact: true }).click();
  await page.getByLabel('搜索公司或岗位').fill(company);
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: `test-results/${testInfo.project.name}-overview.png`, fullPage: true });
  await page.getByRole('button', { name: company, exact: true }).click();
  page.once('dialog', dialog => dialog.accept());
  await detail.getByRole('button', { name: '删除', exact: true }).click();
  await expect(detail).not.toBeVisible();
  await expect(page.getByRole('button', { name: company, exact: true })).toHaveCount(0);
  await expect(page.getByRole('button', { name: '退出登录', exact: true })).toHaveCount(0);
  await page.reload();
  await expect(page.locator('#dashboard')).toBeVisible();
  await expect(page).toHaveURL('http://127.0.0.1:3101/');
  expect(errors).toEqual([]);
});
test('Beijing dates and overdue reminders work from a non-China timezone', async ({ browser }, testInfo) => {
  const context = await browser.newContext({ timezoneId: 'America/Los_Angeles', viewport: testInfo.project.name === 'mobile' ? { width: 393, height: 851 } : { width: 1440, height: 1000 } });
  const page = await context.newPage(); await page.goto('/login');
  await expect(page).toHaveURL('http://127.0.0.1:3101/');
  await expect(page.locator('#dashboard')).toBeVisible();
  const headers = { 'X-Tracker-Request': 'web' };
  const created = await context.request.post('/api/applications', { headers, data: { company: `时区验证-${testInfo.project.name}`, role: '测试岗位', stage: '已投递', applied_at: '2026-09-01T00:30:00+08:00' } });
  const record = await created.json();
  const event = await context.request.post(`/api/applications/${record.id}/events`, { headers, data: { title: '已过期的测评', kind: '测评截止', due_at: '2026-01-01T08:30:00+08:00' } });
  expect(event.ok()).toBeTruthy();
  await page.getByRole('button', { name: '刷新数据' }).click();
  await expect(page.locator('#reminders')).toContainText('已逾期');
  await page.getByRole('button', { name: record.company, exact: true }).click();
  const detail = page.locator('#detail-dialog');
  await expect(detail.locator('.detail-info')).toContainText('2026/09/01 00:30');
  await detail.getByRole('button', { name: '编辑投递 / 更新进度' }).click();
  await expect(page.locator('#editor-dialog').getByLabel('投递时间（北京时间）', { exact: true })).toHaveValue('2026-09-01T00:30');
  await context.close();
});
